services:
  db:
    image: postgres:15
    container_name: mumbai_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mumbai_password
      POSTGRES_DB: mumbai_housing
    ports:
      - "5432:5432"

  spark-master:
    image: bitnami/spark:3.5
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"
      - "7077:7077"

  mumbai_app:
    build: .
    container_name: mumbai_app
    ports:
      - "8501:8501"
    depends_on:
      - db
      - spark-master
    environment:
      - DATABASE_URL=postgresql://admin:mumbai_password@db:5432/mumbai_housing
